# Cenários que falharam na evolução
20
178,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 01:12:28.957,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2525656,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
126,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 00:59:44.54,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1686608,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
213,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 01:20:07.567,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3028541,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
141,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 01:03:05.547,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1900734,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
227,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 01:23:10.04,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
3203783,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
245,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 01:27:43.493,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
3493794,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
177,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 01:12:27.132,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
2525641,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
234,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 01:23:46.248,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3208640,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
262,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 01:31:54.389,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
3780826,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
1,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 00:33:19.852,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
14,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
62,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 00:46:42.152,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
871791,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
134,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 01:02:28.84,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1895065,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
192,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 01:16:47.387,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
2852759,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
42,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 00:41:40.76,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
522667,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
139,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 01:03:02.333,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1900068,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
28,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 00:39:12.793,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
378387,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
79,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 00:50:32.128,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1135238,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
106,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 00:56:22.38,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
1512892,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
20,Entry point for SctpEchoTest.testSimpleEcho,1,2014-08-05 00:35:44.752,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho()
0
1
88775,io.netty.testsuite.transport.sctp.SctpEchoTest.testSimpleEcho(),-1,org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>,1.0
0
-----------------------------------
82,Entry point for SocketConnectionAttemptTest.testConnectCancellation,1,2014-08-05 00:50:48.243,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation()
0
1
1136480,io.netty.testsuite.transport.socket.SocketConnectionAttemptTest.testConnectCancellation(io.netty.bootstrap.Bootstrap),-1,java.lang.AssertionError: 
Expected: is <false>
     but: was <true>,1.0
0
-----------------------------------
